### ISSUE TITLE
.config file is not saved, when you dont  have input topography

### ISSUE THREAD

**Issue by oculus99** [hersfeldtn/koppenpasta#2]
If I select not "Upload topography, I cannot save congif file!

See example program run below ...

That is it:

Load config file? (y/n): n

Land Climate Zones
0: Full Koppen set of 31 climate zones (default)
1: As above, but exclude wet-summer savanna (Aw) / dry-summer savanna (As) distinction (common in formal maps)
2: Reduced set of 14 climate zones (common in worldbuilding circles)
3: Seasonless: Ignore seasonal changes and use annual averages only, producing 9 zones
    (appropriate for very short years or tidal-locked worlds without libration)
4: 5 Koppen Groups (A,B,C,D,E) only
5: Holdridge Life Zones approximation (references only biotemperature and precipitation)
Set Land Climate Zone Type: 0

Sea Climate Zones
0: Set of 4 zones of my own invention; tropical, temperate, seasonal ice, permanent ice (default)
1: As above but exclude tropical/temperate distinction
2: Seasonless: Mark tropical, temperate, and permanent ice based on annual averages
3: As above but exclude tropical/temperate distinction
4: No sea climate zones, just flat blue
5: Exclude seas entirely, produce no output (appropriate for all-land planets)
Set Sea Climate Type: 0

Color List
0: Default (blue rainforest); used by Wikipedia, Artifexian, etc.
1: Alternate (red rainforest); used in some research papers, usually with older definitions (uses same sea zone colors, as those are my invention)
2: "True" color; fills each zone with their average color on Earth, based on satellite imagery (all sea zones except permanent ice given same color)
3: Import custom color list (see defaultcolor.ini for template)
Set Color List: 2

Land/Sea Blend
0: Use land/sea mask in the NetCDF file to blend land and sea climates into a single map:
    tiles marked land show land climate zones, tiles marked sea show sea climate zones (default)
1: Do not blend: Produce distinct land and sea climate maps (appropriate for final output, so you can
    combine them with a high-res land/sea mask yourself)
Set Blend setting: 1

Bin Size
Bins adjacent "months" in the NetCDF file together.
e.g. if you have a NetCDF file with 36 months, a value of "3" will average together data from every 3 months
    to produce 12 months, which will then be used for determining climate zones.
Ideally there should be a whole number of bins per year.
For an input of "1" or "0" the script will not bin months together.
Set Bin Size: 0

Interpolation Rescaling Factor
Multiplies the latitude and longitude of the output and interpolates the climate data up to that resolution
e.g. applying a rescaling factor of 4 to a model with 32x64 resolution will get an output with 128x256 resolution
Interpolation essentially just averages the values of adjacent cells, so isn't as accurate as actual modelling
    and in particular will not reflect the impact of topographical features smaller than those input to ExoPlaSim;
    but it does reflect the underlying data better than trying to interpolate "by eye" from the output maps.
The rescaling factor need not be an integer, but the output must have an integer resolution
    (e.g. you could apply a factor of 2.5 to a 32x64 model to get 80x160 resolution)
CAUTION: High rescaling factors can significantly extend the script's runtime.
Input "0" for no interpolation.
Set Interpolation Rescaling Factor: 1

"Dummy" Sea Ice Cover
Adds "dummy" sea ice to land whenever there is sea ice in at least 1 adjacent cell, before interpolation
This helps ensure sea ice zones remain contiguous with land when interpolated
Add "dummy" sea ice? (y/n): y

Adjust Temperature to Topography
Allows you to upload a higher-resolution heightmap, and then after interpolation, temperature is adjusted
    based on deviation between that heightmap and an interpolated heightmap from the model output.
Precipitation is not adjusted, so this is still not as accurate as higher-resolution modelling,
    but it is an improvement and gives the map some "texture".
Upload Topography? (y/n): n

Configure Climate Zone Definitions? (y/n): n

Config
Saves the above configurations and definitions to a .ini file that can be loaded in later uses of this script to save time.
Note that:
    The configs do not include the input or output filenames
    Loading a config skips the rest of configuration
    The config file can only be altered later by manually opening and editting the .ini file
Save configuration to config file? (y/n): y
Config name: ko
Traceback (most recent call last):
  File "koppenpasta.py", line 1958, in <module>
    'Topography Map': str(topo_save),
NameError: name 'topo_save' is not defined

**Comment by hersfeldtn** [comment]
Should be fixed after 12.4, forgot to close this
